permalink:           pretty

# Setup
title:               'Data Science'
tagline:             'CS SBU'
url:                 https://sk7w4tch3r.github.io/CS-SBU-DataScience
baseurl:             '/CS-SBU-DataScience'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
  name:              Hesam Damghanian
  url:               https://twitter.com/c3nt4ur1
github:


# Custom vars
version:             1.0.0

src:                 "."
default_theme:       "light"

# To use hljs, disable the default highlighter
# We also use a built-in math engine so gotta disable that too
kramdown:
  syntax_highlighter_opts:
    disable : true
  math_engine: null

exclude:
  - README.md

# Chapter Configuration (up to a 2 level nested list)

prologues:
  - path: chapters/prologue.md
    sections:
      - path: chapters/prologue2.md
chapters:
  - path: chapters/chapter1/01.md
    sections:
      - path: chapters/chapter1/01-1.md
      - path: chapters/chapter1/01-2.md
  - path: chapters/chapter2-3/02.md
    sections:
      - path: chapters/chapter2-3/02-1.md
      - path: chapters/chapter2-3/02-q.md
      - path: chapters/chapter2-3/02-a.md
  - path: chapters/chapter4/04.md
    sections:
      - path: chapters/chapter4/04-1.md
      - path: chapters/chapter4/04-2.md
  - path: chapters/chapter5/0
    sections:
      - path: chapters/chapter4/05-1.md
epilogues:
  - path: chapters/epilogue.md
